### ISSUE TITLE
finish the 1.0 milestone release

### ISSUE THREAD

**Issue by spearwolf** [spearwolf/doorkeeper#18]
- [ ] create release info message
- [x] tag the docker image with 1.0
- [ ] tag the git repository
